Repository matsim-org/matsim-libs, pull requests merged in 2020-05, with the labels that each got.

#959 Optional times in pt
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/stopStopTimes/StopStopTimeCalculatorImpl.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/stopStopTimes/StopStopTimeCalculatorSerializable.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/stopStopTimes/StopStopTimeCalculatorTuple.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorImpl.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorSerializable.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeStuckCalculator.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/hook/PTransitAgent.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/operator/CreateOperatorFromTransitSchedule.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/routeProvider/ComplexCircleScheduleProvider.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/routeProvider/SimpleBackAndForthScheduleProvider.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/routeProvider/SimpleCircleScheduleProvider.java
  contribs/minibus/src/main/java/org/matsim/contrib/minibus/routeProvider/TimeAwareComplexCircleScheduleProvider.java
  contribs/multimodal/src/test/java/org/matsim/contrib/multimodal/pt/Fixture.java
  contribs/otfvis/src/main/java/org/matsim/pt/demo/TwoLinesDemo.java
  contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/trafficinfo/deterministic/DeterministicWaitTimeCalculator.java
  contribs/vsp/src/main/java/playground/vsp/analysis/modules/transitSchedule2Shp/TransitRouteData.java
  contribs/vsp/src/main/java/playground/vsp/analysis/modules/transitScheduleAnalyser/TransitScheduleAnalyserToCSVandTEX.java
  contribs/vsp/src/main/java/playground/vsp/andreas/mzilske/pt/queuesim/GreedyUmlaufBuilderImpl.java
  contribs/vsp/src/main/java/playground/vsp/andreas/utils/pt/DelayTracker.java
  matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/pt/AbstractTransitDriverAgent.java
  matsim/src/main/java/org/matsim/pt/router/PreparedTransitSchedule.java
  matsim/src/main/java/org/matsim/pt/router/TransitRouterNetworkTravelTimeAndDisutility.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitRouteStopImpl.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleFactoryImpl.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleReaderV1.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleReaderV2.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleWriterV1.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleWriterV2.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/api/TransitRouteStop.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/api/TransitScheduleFactory.java
  matsim/src/main/java/org/matsim/pt/utils/TransitScheduleValidator.java
  matsim/src/main/java/org/matsim/withinday/utils/EditTrips.java
  matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/Fixture.java
  matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/RaptorStopFinderTest.java
  matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorIntermodalTest.java
  matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/pt/TransitDriverTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/pt/TransitQueueSimulationTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/pt/UmlaufDriverTest.java
  matsim/src/test/java/org/matsim/integration/population/NonAlternatingPlanElementsIT.java
  matsim/src/test/java/org/matsim/pt/router/Fixture.java
  matsim/src/test/java/org/matsim/pt/router/TransitRouterCustomDataTest.java
  matsim/src/test/java/org/matsim/pt/router/TransitRouterImplTest.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitRouteStopTest.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitRouteTest.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitScheduleFactoryTest.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitScheduleFormatV1Test.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitScheduleIOTest.java
  matsim/src/test/java/org/matsim/pt/transitSchedule/TransitScheduleReaderV1Test.java
Labels: automerge

#967 Optional time in QSim / agents
  contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/DynAgent.java
  matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/ActivityEngineDefaultImpl.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/ActivityDurationUtils.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/BasicPlanAgentImpl.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/PlanBasedDriverAgentImpl.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
  matsim/src/main/java/org/matsim/core/population/PopulationUtils.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/AbstractQSimModuleTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/FlowEfficiencyCalculatorTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkTest.java
  matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/VehicleHandlerTest.java
Labels: automerge

#968 refactor OpeningTime
  matsim/src/main/java/org/matsim/facilities/ActivityOptionImpl.java
  matsim/src/main/java/org/matsim/facilities/FacilitiesFromPopulation.java
  matsim/src/main/java/org/matsim/facilities/FacilitiesReaderMatsimV1.java
  matsim/src/main/java/org/matsim/facilities/OpeningTime.java
  matsim/src/main/java/org/matsim/facilities/OpeningTimeImpl.java
Labels: automerge

#969 Optional time in activity scoring
  contribs/locationchoice/src/main/java/org/matsim/contrib/locationchoice/frozenepsilons/DCActivityScoringFunction.java
  contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/scoring/CharyparNagelOpenTimesActivityScoringWithDiagnostics.java
  matsim/src/main/java/org/matsim/core/scoring/functions/ActivityTypeOpeningIntervalCalculator.java
  matsim/src/main/java/org/matsim/core/scoring/functions/ActivityUtilityParameters.java
  matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelActivityScoring.java
  matsim/src/main/java/org/matsim/core/scoring/functions/FacilityOpeningIntervalCalculator.java
  matsim/src/main/java/org/matsim/core/scoring/functions/OpeningIntervalCalculator.java
  matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelActivityScoring.java
  matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelOpenTimesActivityScoring.java
  matsim/src/test/java/org/matsim/core/scoring/functions/CharyparNagelOpenTimesScoringFunctionTest.java
Labels: automerge

#970 refactor roadpricing Cost to use -/+Inf for start/end times instead o…
  contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingReaderXMLv1.java
  contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeImpl.java
  contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingWriterXMLv1.java
Labels: automerge

#971 Finalise removal of undefined time
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/events/EmissionEventsReader.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorImpl.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorSerializable.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeStuckCalculator.java
  contribs/locationchoice/src/main/java/org/matsim/contrib/locationchoice/frozenepsilons/PlanTimesAdapter.java
  contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeWithTollAvoidance.java
  contribs/vsp/src/main/java/playground/vsp/andreas/bvgAna/level1/StopId2RouteId2DelayAtStopMapData.java
  contribs/vsp/src/main/java/playground/vsp/andreas/bvgAna/level2/VehiclePlannedRealizedMissedDepartures.java
  matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java
  matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
  matsim/src/main/java/org/matsim/analysis/PHbyModeCalculator.java
  matsim/src/main/java/org/matsim/api/core/v01/network/Link.java
  matsim/src/main/java/org/matsim/core/network/FixedIntervalTimeVariantAttribute.java
  matsim/src/main/java/org/matsim/core/network/FixedIntervalTimeVariantLinkFactory.java
  matsim/src/main/java/org/matsim/core/network/TimeVariantAttribute.java
  matsim/src/main/java/org/matsim/core/network/VariableIntervalTimeVariantAttribute.java
  matsim/src/main/java/org/matsim/core/network/VariableIntervalTimeVariantLinkFactory.java
  matsim/src/main/java/org/matsim/core/router/AStarLandmarks.java
  matsim/src/main/java/org/matsim/core/router/Dijkstra.java
  matsim/src/main/java/org/matsim/core/router/TripRouter.java
  matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelLegScoring.java
  matsim/src/main/java/org/matsim/core/utils/misc/Time.java
  matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelLegScoring.java
  matsim/src/main/java/org/matsim/pt/analysis/TransitLoad.java
  matsim/src/main/java/org/matsim/pt/router/TransitLeastCostPathTree.java
  matsim/src/main/java/org/matsim/pt/transitSchedule/MinimalTransferTimesImpl.java
  matsim/src/main/java/org/matsim/utils/leastcostpathtree/LeastCostPathTree.java
  matsim/src/test/java/org/matsim/core/network/TimeVariantLinkImplTest.java
  matsim/src/test/java/org/matsim/core/utils/misc/TimeTest.java
  matsim/src/test/java/org/matsim/integration/timevariantnetworks/QSimIntegrationTest.java
Labels: automerge

#976 add unit tests for InsertionGenerator
  contribs/drt/pom.xml
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequest.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
Labels: automerge

#977 add special handling of dropoffs coinciding with the existing stops
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
Labels: automerge

#979 improve tests in freight
  contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeLoaderTest.java
  contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintFromVehiclesFileTest.java
  contribs/freight/test/input/org/matsim/contrib/freight/jsprit/vehicleTypesForDCTest.xml
Labels: automerge

#973 Netcdf writer
  contribs/analysis/src/main/java/org/matsim/contrib/analysis/time/TimeBinMap.java
  contribs/emissions/pom.xml
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/EmissionGridAnalyzer.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/events/EmissionEventsReader.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsToRasterHandler.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/PalmChemistryInput.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/RasteredNetwork.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/utils/EmissionsToRasterHandlerTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/utils/PalmChemistryInputTest.java
  contribs/emissions/test/input/org/matsim/contrib/emissions/utils/EmissionsToRasterHandlerTest/test/output_events.emissions.xml.gz
  matsim/src/main/java/org/matsim/core/network/NetworkImpl.java
Labels: automerge

#982 Add missing injection getter for multi-modal DVRP
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/ModalProviders.java
Labels: automerge

#950 setCoord method for acitivty start events so that coordinate can be retrofitted; some changes in otfvis for infection vis; comment changes
  contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/layer/OGLAgentPointLayer.java
  contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/queries/QueryAgentPlan.java
  matsim/src/main/java/org/matsim/api/core/v01/events/ActivityStartEvent.java
  matsim/src/main/java/org/matsim/core/config/groups/StrategyConfigGroup.java
  matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AbstractAgentSnapshotInfoBuilder.java
  matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java
  matsim/src/main/resources/dtd/population_v6.dtd
  matsim/src/test/java/org/matsim/core/trafficmonitoring/TravelTimeDataArrayTest.java
Labels: automerge

#985 Update README.md
  contribs/discrete_mode_choice/README.md
Labels: automerge

#986 Add nested logit model + red bus / blue bus tests
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNest.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestStructure.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestedTourCandidate.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestedTripCandidate.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/Nest.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestCalculator.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestStructure.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestedLogitSelector.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestedUtilityCandidate.java
  contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/WrappingNestedUtilityCandidate.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/ConstantTripEstimator.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MaximumUtilityTest.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MultinomialLogitTest.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/NestedLogitTest.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/RandomUtilityTest.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/nested/NestCalculatorTest.java
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/modules/config/ConfigTest.java
Labels: automerge

#990 some optimizations and changes
  matsim/src/main/java/org/matsim/core/replanning/strategies/TimeAllocationMutatorModule.java
  matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeCalculator.java
  matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java
  matsim/src/main/java/org/matsim/guice/DependencyGraphControlerListener.java
  matsim/src/main/java/org/matsim/vehicles/MatsimVehicleReader.java
Labels: automerge

#991 documentation
  contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/examples/RunExampleSocialSimulation.java
  contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/package-info.java
  contribs/socnetsim/src/main/javadoc/overview.html
Labels: automerge

#983 More tests for default analysis modules
  matsim/src/main/java/org/matsim/analysis/TripsAndLegsCSVWriter.java
  matsim/src/main/java/org/matsim/core/router/TripStructureUtils.java
  matsim/src/test/java/org/matsim/analysis/PHbyModeCalculatorTest.java
  matsim/src/test/java/org/matsim/analysis/PKMbyModeCalculatorTest.java
  matsim/src/test/java/org/matsim/analysis/Plans.java
  matsim/src/test/java/org/matsim/analysis/ScoreStatsControlerListenerTest.java
  matsim/src/test/java/org/matsim/analysis/TripsAndLegsCSVWriterTest.java
Labels: automerge

#992 add link to javadoc
  contribs/socnetsim/README.md
Labels: automerge

#993 Gaussian blur for emissions
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/FastEmissionGridAnalyzer.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/Raster.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/RawEmissionEventsReader.java
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/RasteredNetwork.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/EmissionGridAnalyzerTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/EmissionsByPollutantTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/EmissionsOnLinkEventHandlerTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/FastEmissionGridAnalyzerTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/RasterTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/RawEmissionEventsReaderTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/utils/EmissionUtilsTest.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/utils/TestUtils.java
Labels: automerge

#997 Add a Collector for networks
  matsim/src/main/java/org/matsim/core/network/NetworkCollector.java
  matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
  matsim/src/test/java/org/matsim/core/network/NetworkCollectorTest.java
Labels: automerge, enhancement

#998 Fix boundary condition of line raster algorithm to make it compatible…
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/FastEmissionGridAnalyzer.java
  contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/FastEmissionGridAnalyzerTest.java
Labels: automerge, bug

#999 don't attach release-zip files to build
  benchmark/pom.xml
  contribs/pom.xml
  distribution/pom.xml
  matsim/pom.xml
Labels: automerge

#1000 Add hint in error message
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngine.java
Labels: automerge
