Repository matsim-org/matsim-libs, pull requests merged in 2021-02, with the labels that each got.

#1364 attempt at speeding up income dependent utility of money: use IdMap, …
  contribs/vsp/src/main/java/playground/vsp/scoring/IncomeDependentUtilityOfMoneyPersonScoringParameters.java
Labels: automerge

#1366 rename (misleading) performance indicator from revenue distance to pa…
  contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTripsAnalyser.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtVehicleDistanceStats.java
Labels: automerge, enhancement

#1368 typo
  contribs/discrete_mode_choice/docs/GettingStarted.md
Labels: automerge

#1372 deprecate ExperimentalTransitRouteFactory and replace it where possible
  contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/components/utils/ScheduleWaitingTimeEstimatorTest.java
  contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeStuckCalculator.java
  contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/PlanSerializable.java
  matsim/src/main/java/org/matsim/pt/routes/ExperimentalTransitRouteFactory.java
  matsim/src/test/java/org/matsim/analysis/Plans.java
Labels: automerge

#1373 DRT: make RequestInsertionScheduler an interface
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java
  contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
Labels: automerge

#1375 DRT: remove VehicleData, make VehicleEntry top-level class
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleData.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleEntry.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionWithDetourData.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
  contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/EDrtVehicleDataEntryFactory.java
  contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
Labels: automerge

#1376 DRT: add tests for BestInsertionFinder
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinderTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
Labels: automerge

#1377 DRT: cleanup and tests for KNearestInsertionsAtEndFilter
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleEntry.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
Labels: automerge

#1379 DVRP: use custom comparator in PartialSort to allow for deterministic tie-breaking
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinder.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
  contribs/dvrp/src/main/java/org/matsim/contrib/util/PartialSort.java
  contribs/dvrp/src/main/java/org/matsim/contrib/util/StraightLineKnnFinder.java
  contribs/dvrp/src/test/java/org/matsim/contrib/util/PartialSortTest.java
  contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentETaxiOptimizer.java
Labels: automerge

#1380 DRT: add unit tests for SingleInsertionDetourPathCalculator
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculatorTest.java
Labels: automerge

#1381 DRT: add no-detour case to SingleInsertionDetourPathCalculator tests
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculatorTest.java
Labels: automerge

#1382 DRT: add unit tests for MultiInsertionDetourPathCalculator
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculatorTest.java
Labels: automerge

#1384 Make DRT stops attributable
  contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacility.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacilityImpl.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
Labels: automerge, enhancement

#1385 DRT: generalise insertion search with insertion providers
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProvider.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
Labels: automerge

#1387 DRT: fix DefaultDrtInsertionSearch: do not find best insertion if none provided
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearch.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DrtPoolingParameterTest.java
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathSearch.java
Labels: automerge

#1388 DRT: add extensive insertion provider tests
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchParams.java
  contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProviderTest.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ForkJoinPoolTestRule.java
  contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
  contribs/dvrp/src/main/java/org/matsim/contrib/util/PartialSort.java
  contribs/dvrp/src/test/java/org/matsim/contrib/util/PartialSortTest.java
Labels: automerge

#1390 Make most methofds in JointDemandUtils public
  contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandCarExample.java
  contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandDRTExample.java
  contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/JointDemandUtils.java
  contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandCarExampleIT.java
  contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandDRTExampleIT.java
Labels: automerge

#1391 Freight: reduce logging level
  contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgent.java
Labels: automerge

#1392 Emissions: Minor fix in decision if average table is needed or not
  contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java
Labels: automerge

#1393 remove deprecated freightUtils.runJsprit(scenario, fcg) and only use …
  contribs/freight/src/main/java/org/matsim/contrib/freight/utils/FreightUtils.java
  contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintFromVehiclesFileTest.java
  contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintTest.java
  contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/IntegrationIT.java
  contribs/freight/src/test/java/org/matsim/contrib/freight/utils/FreightUtilsTest.java
Labels: automerge

#1395 add reflection to RLS 19 noise immission
  contribs/noise/src/main/java/org/matsim/contrib/noise/BarrierContext.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/Grid.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseComputationModule.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseImmission.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseTimeTracker.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/RLS19NoiseImmission.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/RLS90NoiseImmission.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/ReflectionContext.java
  contribs/noise/src/main/java/org/matsim/contrib/noise/ShieldingContext.java
  contribs/noise/src/test/java/org/matsim/contrib/noise/NoiseRLS19IT.java
Labels: enhancement

#1220 remove Thread as the parent class from QSim
  matsim/src/main/java/org/matsim/core/mobsim/qsim/QSim.java
Labels: automerge

#1396 ChargingWithAssignmentLogicInterface
  contribs/drt/src/main/java/org/matsim/contrib/edrt/scheduler/EmptyVehicleChargingScheduler.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithAssignmentLogic.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingAndAssignmentLogic.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingActivity.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingTask.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingTaskImpl.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyTimeProfileCollectorProvider.java
  contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyXYDataProvider.java
  contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
  contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentChargerPlugData.java
Labels: automerge

#1403 Save/load dvrp travel times
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimeEstimator.java
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimes.java
  contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpTravelTimeModule.java
  contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimeEstimatorTest.java
  contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimesTest.java
  matsim/src/main/java/org/matsim/core/trafficmonitoring/TimeBinUtils.java
Labels: automerge
