Repository matsim-org/matsim-libs, pull requests merged in 2025-06, with the labels that each got.

#3981 feat(freight(carrier)): run CarrierConsistencyCheck when using CarrierUtils.runJsprit()
  contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
  contribs/freight/src/main/java/org/matsim/freight/carriers/consistency_checkers/CarrierConsistencyCheckers.java
Labels: enhancement

#3997 feat(freight:carriers): Take roadpricing into account when running jsprit from CarrierUtils.runJsprit(...)
  contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
  contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/NetworkBasedTransportCosts.java
Labels: enhancement

#4003 build(deps): bump geotools.version from 33.0 to 33.1
  pom.xml
Labels: dependencies

#4004 build(deps): bump graphhopper-core from 9.1 to 10.2
  contribs/vsp/pom.xml
Labels: dependencies

#4005 build(deps): bump osm4j-pbf and osm4j-xml from 1.3.0 to 1.4.1
  contribs/osm/pom.xml
  contribs/signals/pom.xml
Labels: dependencies

#4068 fix(deps): add junit-jupiter-api to dependency management
  pom.xml
Labels: dependencies

#4071 build(deps): bump commons-logging:commons-logging from 1.2 to 1.3.5
  pom.xml
Labels: dependencies, java
